# For rules: https://beta.ruff.rs/docs/rules
select = [ "E", "F", "B", "I" ]
ignore = [ "C901", "E701", "E402", "D203", "E211", "I001", "B904", "B008", "B905", "B028", "E741" ,"B007"]

# Selector
exclude = [ ".git", ".vscode", "log", "temp", "venv", "old", "build", "dist" ]

# By default, always show source code snippets.
show-source = true

# statistics = True
line-length = 180
